module.exports = {
  root: true,
  env: { browser: true, es2020: true },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:prettier/recommended',
    'plugin:react-hooks/recommended',
  ],
  ignorePatterns: [ 'dist', '.eslintrc.cjs' ],
  overrides: [],
  parser: '@typescript-eslint/parser',
  plugins: [
    'react-refresh',
    'react',
    'react-hooks',
    '@typescript-eslint',
    'import',
    'prettier',
  ],
  settings: {
    react: {
      version: 'detect',
    },
  },
  rules: {
    'react-refresh/only-export-components': [
      'warn',
      { allowConstantExport: true },
    ],
    semi: 0,
    'react/react-in-jsx-scope': 0,
    'no-console': 1,
    '@typescript-eslint/no-explicit-any': 0,
    '@typescript-eslint/explicit-module-boundary-types': 0,
    '@typescript-eslint/ban-ts-comment': 0,
    '@typescript-eslint/no-var-requires': 0,
    '@typescript-eslint/no-unused-vars': 1,
    '@typescript-eslint/no-this-alias': 0,
    '@typescript-eslint/no-empty-function': 0,
    'no-await-in-loop': 2,
    'no-empty': [ 2, { allowEmptyCatch: true } ],
    'prefer-const': 1,
    'import/no-anonymous-default-export': 0,
    eqeqeq: 2,
    'no-empty-function': 0,
    'no-self-compare': 2,
    'prettier/prettier': 0,
    'no-undef': 0,
    'react/display-name': 0,
    'react/jsx-key': 1,
    'require-await': 0,
    'react-hooks/rules-of-hooks': 1,
    'react-hooks/exhaustive-deps': 1,
    'no-unreachable': 1,
    'import/extensions': [
      1,
      'ignorePackages',
      {
        '': 'never',
        js: 'never',
        jsx: 'never',
        ts: 'never',
        tsx: 'never',
      },
    ],
    'import/newline-after-import': 1,
    'import/no-namespace': 1,
    'import/order': [
      1,
      {
        groups: [
          'builtin',
          'external',
          'internal',
          [ 'sibling', 'parent' ],
          'index',
          'object',
          'type',
          'unknown',
        ],
        pathGroups: [
          {
            pattern: 'react',
            group: 'external',
            position: 'before',
          },
          {
            pattern: '@(?!/).*', // scoped-package
            group: 'external',
            position: 'after',
          },
          {
            pattern: '@/*',
            group: 'internal',
            position: 'before',
          },
          {
            pattern: '@/*',
            group: 'type',
            position: 'after',
          },
        ],
        pathGroupsExcludedImportTypes: [ 'react', 'next' ],
        'newlines-between': 'always',
        alphabetize: {
          order: 'asc',
          caseInsensitive: true,
        },
      },
    ],
  },
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    project: './tsconfig.json',
    tsconfigRootDir: __dirname,
    EXPERIMENTAL_useProjectService: {
      // allowDefaultProjectForFiles: ['./*.tsx'],
      maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING: Infinity,
    },
  },
};
